# Generated by Django 3.2.5 on 2021-08-27 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cname',
            field=models.CharField(default='', max_length=50),
        ),
    ]
